config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :students
  resources :presences
  resources :classrooms
  resources :schedules
  resources :seances
  resources :classes
  resources :subjects
  resources :module_subjects
  resources :professors
  resources :users

  get 'suivi' => 'suivi#index'

end

app/models/classe.rb
class Classe < ActiveRecord::Base
	has_one :schedule
	has_many :students
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_one :classroom
	has_one :subject
	belongs_to :schedule
end

app/models/module_subject.rb
class ModuleSubject < ActiveRecord::Base
end

app/models/presence.rb
class Presence < ActiveRecord::Base
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :meetings
	belongs_to :classe
end

app/models/seance.rb
class Seance < ActiveRecord::Base
	has_one :subject
	has_one :class
	belongs_to :schedule
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :module_subject
  belongs_to :meeting
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :professors
	has_many :students
	attr_accessor :professor_grade , :user_id , :student_special_info
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.all
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)

    respond_to do |format|
      if @presence.save
        format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    respond_to do |format|
      format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:in_class, :out_class, :boitier , :professor_id , :student_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/suivi_helper.rb
module SuiviHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/presences/_form.html.erb
<%= form_for(@presence) do |f| %>
  <% if @presence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presence.errors.count, "error") %> prohibited this presence from being saved:</h2>

      <ul>
      <% @presence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in_class %><br>
    <%= f.datetime_select :in_class %>
  </div>
  <div class="field">
    <%= f.label :out_class %><br>
    <%= f.datetime_select :out_class %>
  </div>
  <div class="field">
    <%= f.label :boitier %><br>
    <%= f.text_field :boitier %>
  </div>

  <div class="field">
    <%= f.label :professor_id %><br>
    <%= f.text_field :professor_id %>
  </div>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presences/edit.html.erb
<h1>Editing Presence</h1>

<%= render 'form' %>

<%= link_to 'Show', @presence %> |
<%= link_to 'Back', presences_path %>

app/views/presences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Presences</h1>

<table>
  <thead>
    <tr>
      <th>In class</th>
      <th>Out class</th>
      <th>Boitier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presences.each do |presence| %>
      <tr>
        <td><%= presence.in_class %></td>
        <td><%= presence.out_class %></td>
        <td><%= presence.boitier %></td>
        <td><%= link_to 'Show', presence %></td>
        <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
        <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presence', new_presence_path %>

app/views/presences/new.html.erb
<h1>New Presence</h1>

<%= render 'form' %>

<%= link_to 'Back', presences_path %>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In class:</strong>
  <%= @presence.in_class %>
</p>

<p>
  <strong>Out class:</strong>
  <%= @presence.out_class %>
</p>

<p>
  <strong>Boitier:</strong>
  <%= @presence.boitier %>
</p>

<p>
  <strong>Professor:</strong>
  <%= Professor.where(id: @presence.professor_id) %>
</p>

<p>
  <strong>Student:</strong>
  <%= @student = Student.where(id: @presence.student_id) %>
</p>

<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>