config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :students
  resources :presences
  resources :classrooms
  resources :schedules
  resources :seances
  resources :classes
  resources :subjects
  resources :module_subjects
  resources :professors
  resources :users

  get 'suivi' => 'suivi#index'

end

app/models/classe.rb
class Classe < ActiveRecord::Base
	has_one :schedule
	has_many :students
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_one :classroom
	has_one :subject
	belongs_to :schedule
end

app/models/module_subject.rb
class ModuleSubject < ActiveRecord::Base
end

app/models/presence.rb
class Presence < ActiveRecord::Base
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :meetings
	belongs_to :classe
end

app/models/seance.rb
class Seance < ActiveRecord::Base
	has_one :subject
	has_one :class
	belongs_to :schedule
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :module_subject
  belongs_to :meeting
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :professors
	has_many :students
	attr_accessor :professor_grade , :user_id , :student_special_info
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:start_time, :end_time, :actual_date , :schedule_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/suivi_helper.rb
module SuiviHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :actual_date %><br>
    <%= f.datetime_select :actual_date %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br>
    <%= f.text_field :schedule_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Actual date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= meeting.actual_date %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
  <strong>Actual date:</strong>
  <%= @meeting.actual_date %>
</p>
<p>
  <strong>Schedule:</strong>
  <%= @meeting.schedule_id %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>