config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :students
  resources :presences
  resources :classrooms
  resources :schedules
  resources :seances
  resources :classes
  resources :subjects
  resources :module_subjects
  resources :professors
  resources :users

  get 'suivi' => 'suivi#index'

end

app/models/classe.rb
class Classe < ActiveRecord::Base
	has_one :schedule
	has_many :students
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_one :classroom
	has_one :subject
	belongs_to :schedule
end

app/models/module_subject.rb
class ModuleSubject < ActiveRecord::Base
end

app/models/presence.rb
class Presence < ActiveRecord::Base
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :meetings
	belongs_to :classe
end

app/models/seance.rb
class Seance < ActiveRecord::Base
	has_one :subject
	has_one :class
	belongs_to :schedule
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :module_subject
  belongs_to :meeting
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :professors
	has_many :students
	attr_accessor :professor_grade , :user_id , :student_special_info
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:schedule_name, :schedule_year , :classe_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/suivi_helper.rb
module SuiviHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :schedule_name %><br>
    <%= f.text_field :schedule_name %>
  </div>
  <div class="field">
    <%= f.label :schedule_year %><br>
    <%= f.datetime_select :schedule_year %>
  </div>
  <div class="field">
    <%= f.label :classe_id %><br>
    <%= f.text_field :classe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Schedule name</th>
      <th>Schedule year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.schedule_name %></td>
        <td><%= schedule.schedule_year %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schedule name:</strong>
  <%= @schedule.schedule_name %>
</p>

<p>
  <strong>Schedule year:</strong>
  <%= @schedule.schedule_year %>
</p>

<p>
  <strong>Schedule seances:</strong>
  <% @seances = Seance.where(id: @schedule.id) %>
  <%= @seances.count %>
  <% if @seances.count > 0 %>
	  
	  	<%= @seances %>
	  
  <% end %>
</p>


<p>
  <strong>Class id</strong>
  <%= @schedule.classe_id %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>