config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :students
  resources :presences
  resources :classrooms
  resources :schedules
  resources :seances
  resources :classes
  resources :subjects
  resources :module_subjects
  resources :professors
  resources :users

  get 'suivi' => 'suivi#index'

end

app/models/classe.rb
class Classe < ActiveRecord::Base
	has_one :schedule
	has_many :students
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_one :classroom
	has_one :subject
	belongs_to :schedule
end

app/models/module_subject.rb
class ModuleSubject < ActiveRecord::Base
end

app/models/presence.rb
class Presence < ActiveRecord::Base
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :meetings
	belongs_to :classe
end

app/models/seance.rb
class Seance < ActiveRecord::Base
	has_one :subject
	has_one :class
	belongs_to :schedule
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :presences
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :module_subject
  belongs_to :meeting
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :professors
	has_many :students
	attr_accessor :professor_grade , :user_id , :student_special_info
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :set_class, only: [:show, :edit, :update, :destroy]

  # GET /classes
  # GET /classes.json
  def index
    
    @classes = Classe.all

  end

  # GET /classes/1
  # GET /classes/1.json
  def show
  end

  # GET /classes/new
  def new
    @classe = Classe.new
  end

  # GET /classes/1/edit
  def edit
  end

  # POST /classes
  # POST /classes.json
  def create
    @classe = Classe.new(classe_params)

    respond_to do |format|
      if @classe.save
        format.html { redirect_to @classe, notice: 'Classe was successfully created.' }
        format.json { render :show, status: :created, location: @classe }
      else
        format.html { render :new }
        format.json { render json: @classe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classes/1
  # PATCH/PUT /classes/1.json
  def update
    respond_to do |format|
      if @classe.update(class_params)
        format.html { redirect_to @classe, notice: 'Classe was successfully updated.' }
        format.json { render :show, status: :ok, location: @classe }
      else
        format.html { render :edit }
        format.json { render json: @classe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classes/1
  # DELETE /classes/1.json
  def destroy
    @classe.destroy
    respond_to do |format|
      format.html { redirect_to classes_url, notice: 'Classe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class
      @classe = Classe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classe_params
      params.require(:classe).permit(:class_name, :class_capacity, :class_specific_id)
    end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/suivi_helper.rb
module SuiviHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classes/_form.html.erb
<%= form_for(@classe) do |f| %>
  <% if @classe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@class.errors.count, "error") %> prohibited this class from being saved:</h2>

      <ul>
      <% @class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name %>
  </div>
  <div class="field">
    <%= f.label :class_capacity %><br>
    <%= f.number_field :class_capacity %>
  </div>
  <div class="field">
    <%= f.label :class_specific_id %><br>
    <%= f.text_field :class_specific_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classes/edit.html.erb
<h1>Editing Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @class %> |
<%= link_to 'Back', classes_path %>

app/views/classes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Timber</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/font-awesome.css">
    <link rel="stylesheet" type="text/css" href="css/plugin.css">
    <link rel='stylesheet' id='camera-css'  href='css/camera.css' type='text/css' media='all'>

    <link rel="stylesheet" type="text/css" href="css/slicknav.css">
    <link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="css/style.css">


    

    <script>
      jQuery(function(){
          jQuery('#camera_wrap_1').camera({
          transPeriod: 500,
          time: 3000,
          height: '490px',
          thumbnails: false,
          pagination: true,
          playPause: false,
          loader: false,
          navigation: false,
          hover: false
        });
      });
    </script>
    
  </head>
  <body>
    
   
    
    <div id="about">
      <div class="line2">

    </div>
    <div class="">
      <div class="row">
        <div class="col-md-12 wwa">
          <span name="about" ></span>
          <h3>Suivi des classes en temps réel !</h3>
          <h4>Vous pouvez consulter les classes, les professeurs et les étuiants présents en un seul clic en temps réel !!</h4>
        </div>
      </div>
    </div>
    <div class="">
      <div class="row team">
        <div class="col-md-4 b1">
            <h4>Classe A2</h4> <br>
            <div class="my-progress-bar"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:60%  ; font-size: 150%;">
                60% de temps écoulé
              </div>
            </div>
            <h4>Dr Kamel Ben Rhouma</h4>
            <h5>Professeur de C++</h5>
            <p>Matière: C++ <br/>
            <p>Séance démarrée à : 08h35 <br/>
            <p>Présence des étudiants : 78% <br/>
            </p>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>
      
      
        <div class="col-md-4 b1">
            <h4>Classe B5</h4> <br>
            <div class="my-progress-bar1"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:89%  ; font-size: 150%;">
                89% de temps écoulé
              </div>
            </div>
            <h4>Dr Majdi Jribi</h4>
            <h5>Docteur réseau</h5>
            <p>Matière: Réseau 1 <br/>
            <p>Séance démarrée à : 08h47 <br/>
            <p>Présence des étudiants : 56% <br/>
            </p>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>

        <div class="col-md-4 b1">
            <h4>Classe A4</h4> <br>
            <div class="my-progress-bar2"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:55%  ; font-size: 150%;">
                55% de temps écoulé
              </div>
            </div>
            <h4>Dr Ibtihel Fliss</h4>
            <h5>Enseignante Web</h5>
            <p>Matière: Développement web <br/>
            <p>Séance démarrée à : 08h42 <br/>
            <p>Présence des étudiants : 93% <br/>
            </p>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12 hr1">
              <hr/>
            </div>
          </div>
        </div>

        <div class="col-md-4 b1">
            <h4>Classe SI</h4> <br>
            <div class="my-progress-bar3"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:30% ; font-size: 150%;">
                42% de temps écoulé
              </div>
            </div>

            <h4>Dr Imed Abdessalem</h4>
            <h5>Enseignante embarqué</h5>
            <p>Matière: Développement embarqué <br/>
            <p>Séance démarrée à : 08h58 <br/>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>

        <div class="col-md-4 b1">
            <h4>Classe A4</h4> <br>
            <div class="my-progress-bar4"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:30% ; font-size: 150%;">
                42% de temps écoulé
              </div>
            </div>
            <h4>Dr Ibtihel Fliss</h4>
            <h5>Enseignante C</h5>
            <p>Matière: Développement C <br/>
            <p>Séance démarrée à : 08h42 <br/>
            </p>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>

        <div class="col-md-4 b1">
            <h4>Classe SI</h4> <br>
            <div class="my-progress-bar5"></div>
            <div class="progress" style=" height: 30px;">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
              aria-valuemin="0" aria-valuemax="100" style="width:52% ; font-size: 150%;">
                52% de temps écoulé
              </div>
            </div>

            <h4>Dr Imed Abdessalem</h4>
            <h5>Enseignante embarqué</h5>
            <p>Matière: Développement embarqué <br/>
            <p>Séance démarrée à : 08h58 <br/>
            <ul>
              <li><a href="detail_class.html"><button class="btn btn-default">Détails</button></a></li>
            </ul>
        </div>


      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12 hr1">
          <hr/>
        </div>
      </div>
    </div>    


    

    
   
    
    
  
    
  <script src="js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.slicknav.js"></script>
  <script>
      $(document).ready(function(){
      $(".bhide").click(function(){
        $(".hideObj").slideDown();
        $(this).hide(); //.attr()
        return false;
      });
      $(".bhide2").click(function(){
        $(".container.hideObj2").slideDown();
        $(this).hide(); // .attr()
        return false;
      });
        
      $('.heart').mouseover(function(){
          $(this).find('i').removeClass('fa-heart-o').addClass('fa-heart');
        }).mouseout(function(){
          $(this).find('i').removeClass('fa-heart').addClass('fa-heart-o');
        });
        
        function sdf_FTS(_number,_decimal,_separator)
        {
        var decimal=(typeof(_decimal)!='undefined')?_decimal:2;
        var separator=(typeof(_separator)!='undefined')?_separator:'';
        var r=parseFloat(_number)
        var exp10=Math.pow(10,decimal);
        r=Math.round(r*exp10)/exp10;
        rr=Number(r).toFixed(decimal).toString().split('.');
        b=rr[0].replace(/(\d{1,3}(?=(\d{3})+(?:\.\d|\b)))/g,"\$1"+separator);
        r=(rr[1]?b+'.'+rr[1]:b);

        return r;
}
        
      setTimeout(function(){
          $('#counter').text('0');
          $('#counter1').text('0');
          $('#counter2').text('0');
          setInterval(function(){
            
            var curval=parseInt($('#counter').text());
            var curval1=parseInt($('#counter1').text().replace(' ',''));
            var curval2=parseInt($('#counter2').text());
            if(curval<=707){
              $('#counter').text(curval+1);
            }
            if(curval1<=12280){
              $('#counter1').text(sdf_FTS((curval1+20),0,' '));
            }
            if(curval2<=245){
              $('#counter2').text(curval2+1);
            }
          }, 2);
          
        }, 500);
      });
  </script>
  <script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery('#menu').slicknav();
    
  });
  </script>
  
  <script type="text/javascript">
    $(document).ready(function(){
       
        var $menu = $("#menuF");
            
        $(window).scroll(function(){
            if ( $(this).scrollTop() > 100 && $menu.hasClass("default") ){
                $menu.fadeOut('fast',function(){
                    $(this).removeClass("default")
                           .addClass("fixed transbg")
                           .fadeIn('fast');
                });
            } else if($(this).scrollTop() <= 100 && $menu.hasClass("fixed")) {
                $menu.fadeOut('fast',function(){
                    $(this).removeClass("fixed transbg")
                           .addClass("default")
                           .fadeIn('fast');
                });
            }
        });
  });
    //jQuery
  </script>
  <script>
    /*menu*/
    function calculateScroll() {
      var contentTop      =   [];
      var contentBottom   =   [];
      var winTop      =   $(window).scrollTop();
      var rangeTop    =   200;
      var rangeBottom =   500;
      $('.navmenu').find('a').each(function(){
        contentTop.push( $( $(this).attr('href') ).offset().top );
        contentBottom.push( $( $(this).attr('href') ).offset().top + $( $(this).attr('href') ).height() );
      })
      $.each( contentTop, function(i){
        if ( winTop > contentTop[i] - rangeTop && winTop < contentBottom[i] - rangeBottom ){
          $('.navmenu li')
          .removeClass('active')
          .eq(i).addClass('active');        
        }
      })
    };
    
    $(document).ready(function(){
      calculateScroll();
      $(window).scroll(function(event) {
        calculateScroll();
      });
      $('.navmenu ul li a').click(function() {  
        $('html, body').animate({scrollTop: $(this.hash).offset().top - 80}, 800);
        return false;
      });
    });   
  </script> 
  <script type="text/javascript" charset="utf-8">

    jQuery(document).ready(function(){
      jQuery(".pretty a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true, social_tools: ''});
      
    });
  </script>
  </body>
  
</html>

<style type="text/css">

            body{
                background-color: #f5f5f5;
                margin: 0;
                padding: 0;
                font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            }

            .page {
                margin: 40px;
            }

            h1{
                margin: 40px 0 60px 0;
            }

            .dark-area {
                background-color: #666;
                padding: 40px;
                margin: 0 -40px 20px -40px;
                clear: both;
            }

            .clearfix:before,.clearfix:after {content: " "; display: table;}
            .clearfix:after {clear: both;}
            .clearfix {*zoom: 1;}

</style>


<p id="notice"><%= notice %></p>

<h1>Listing Classes</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Class capacity</th>
      <th>Class specific</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classes.each do |c| %>
      <tr>
        <td><%= c.class_name %></td>
        <td><%= c.class_capacity %></td>
        <td><%= c.class_specific_id %></td>
        <td><%= link_to 'Show', c %></td>
        <td><%= link_to 'Edit', edit_class_path(c) %></td>
        <td><%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classe', new_class_path %>

app/views/classes/new.html.erb
<h1>New Class</h1>

<%= render 'form' %>

<%= link_to 'Back', classes_path %>

app/views/classes/show.html.erb
<!-- <%#= link_to 'Edit', edit_class_path(@classe) %> | -->
<%#= link_to 'Back', classes_path %>



<!DOCTYPE html>
<html lang="en">
  <head>
		<title>Timber</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome.css">
		<link rel='stylesheet' id='camera-css'  href='css/camera.css' type='text/css' media='all'>

		<link rel="stylesheet" type="text/css" href="css/slicknav.css">
		<link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="css/style.css">
		
		
		<script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>

		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700|Open+Sans:700' rel='stylesheet' type='text/css'>
		<script type="text/javascript" src="js/jquery.mobile.customized.min.js"></script>
		<script type="text/javascript" src="js/jquery.easing.1.3.js"></script> 
		<script type="text/javascript" src="js/camera.min.js"></script>
		<script type="text/javascript" src="js/myscript.js"></script>
		<script src="js/sorting.js" type="text/javascript"></script>
		<script src="js/jquery.isotope.js" type="text/javascript"></script>
		<!--script type="text/javascript" src="js/jquery.nav.js"></script-->
		

		<script>
			jQuery(function(){
					jQuery('#camera_wrap_1').camera({
					transPeriod: 500,
					time: 3000,
					height: '490px',
					thumbnails: false,
					pagination: true,
					playPause: false,
					loader: false,
					navigation: false,
					hover: false
				});
			});
		</script>
		
	</head>
	<body>
    

    <!--about start-->    
    
    <div id="about">

		<div class="container">
			<div class="row">
				<div class="col-md-12 wwa">
					<span name="about" ></span>
					<h3><%= @classe.class_name %></h3><%= @classe.class_capacity %> étudiants
					
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row team">
				<div class="col-md-4 b1">

						<%= image_tag ( "picTeam/picT2.png" )  , style: "height: 50.5px; width: 50;" %>

						<h4>Dr Kamel Ben Rhouma</h4>
						<h5>Professeur de C++</h5>
						<p>Matière: C++ <br/>

				</div>

				<div class="col-md-3 bar">
					<div class="textP">
						<h3>Pourcentage de présence</h3>
						<p> </p>
					</div>

					<div class="progB chart" data-percent="64"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="64">
							  <span class="percent">64</span>
							</div>
						</div>
					</div>
					
				</div>

				<div class="col-md-3 bar ">
				<div class="textP">
						<h3>Ponctualité du professeur</h3>
						
					</div>
					<div class="progB chart" data-percent="97"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="97">
							  <span class="percent">97</span>
							</div>
						</div>
					</div>
					
				</div>





			</div>
		</div>


		<div class="container">
			<div class="row aboutUs">
				<div class="col-md-12 ">
					<h3>Tableau des étudiants</h3>
				</div>
				<br>
			</div>
		</div>
		
		<div style="position: relative;">
		


			<table class="table table-hover">
				  <thead>
				    <tr>
				      <th></th>
				      <th>Nom</th>
				      <th>Prénom</th>
				      <th>Présence</th>
				    </tr>
				  </thead>
				  <tbody>
				  <% @class_students = Student.where(classe_id: @classe.id)%>
					<% @class_students.each do |s|%>

					
				    <tr>
				      <th scope="row"><%= image_tag ( "picTeam/picT2.png" )  , style: "height: 50.5px; width: 50;" %></th>
				      <td><%= s.student_special_info %></td>
				      <td><%= s.student_special_info %></td>
				      <td>Présente</td>
				    </tr>
				    <% end %>

				  </tbody>
				</table>
		
		</div>
    </div>


		<div class="container">
			<div class="row">
				<div class="col-md-12 hr1">
					<hr/>
				</div>
			</div>
		</div>		
		<div class="container">
			<div class="row">
				<div class="col-md-3 bar">
					<div class="progB chart" data-percent="16"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="16">
							  <span class="percent">16</span>
							</div>
						</div>
					</div>
					<div class="textP">
						<h3>Pourcentage d'absence</h3>
						<p>Nulla consectetur ornare nibh, a auctor <br/>mauris scelerisque eu proin nec urna quis. </p>
					</div>
				</div>
				<div class="col-md-3 bar">
					<div class="progB chart" data-percent="22"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="22">
							  <span class="percent">22</span>
							</div>
						</div>
					</div>
					<div class="textP">
						<h3>Pourcentage de retard</h3>
						<p>Nulla consectetur ornare nibh, a auctor <br/>mauris scelerisque eu proin nec urna quis. </p>
					</div>
				</div>
				<div class="col-md-3 bar ">
					<div class="progB chart" data-percent="84"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="22">
							  <span class="percent">84</span>
							</div>
						</div>
					</div>
					<div class="textP">
						<h3>Pourcentage de présence</h3>
						<p>Nulla consectetur ornare nibh, a auctor <br/>mauris scelerisque eu proin nec urna quis. </p>
					</div>
				</div>
				<div class="col-md-3 bar ">
					<div class="progB chart" data-percent="97"  data-animate="3500">
						<div class="chart chart-content">
							<div class="percentage" data-percent="97">
							  <span class="percent">97</span>
							</div>
						</div>
					</div>
					<div class="textP">
						<h3>Ponctualité du professeur</h3>
						<p>Nulla consectetur ornare nibh, a auctor <br/>mauris scelerisque eu proin nec urna quis. </p>
					</div>
				</div>
				<br>

				

			</div>
		</div>	

		Schedule for this class :<br>
		<% @schedules = Schedule.where(classe_id: @classe.id) %>
		<% if @schedules.count > 0 %>
			<% @schedules.each do |s| %>
			<%= s.schedule_name %>
			<% end %>
		<% end %>
		
		
		
    
    
   
		
		
	<script src="js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.js"></script>
	<script>
			$(document).ready(function(){
			$(".bhide").click(function(){
				$(".hideObj").slideDown();
				$(this).hide(); //.attr()
				return false;
			});
			$(".bhide2").click(function(){
				$(".container.hideObj2").slideDown();
				$(this).hide(); // .attr()
				return false;
			});
				
			$('.heart').mouseover(function(){
					$(this).find('i').removeClass('fa-heart-o').addClass('fa-heart');
				}).mouseout(function(){
					$(this).find('i').removeClass('fa-heart').addClass('fa-heart-o');
				});
				
				function sdf_FTS(_number,_decimal,_separator)
				{
				var decimal=(typeof(_decimal)!='undefined')?_decimal:2;
				var separator=(typeof(_separator)!='undefined')?_separator:'';
				var r=parseFloat(_number)
				var exp10=Math.pow(10,decimal);
				r=Math.round(r*exp10)/exp10;
				rr=Number(r).toFixed(decimal).toString().split('.');
				b=rr[0].replace(/(\d{1,3}(?=(\d{3})+(?:\.\d|\b)))/g,"\$1"+separator);
				r=(rr[1]?b+'.'+rr[1]:b);

				return r;
}
				
			setTimeout(function(){
					$('#counter').text('0');
					$('#counter1').text('0');
					$('#counter2').text('0');
					setInterval(function(){
						
						var curval=parseInt($('#counter').text());
						var curval1=parseInt($('#counter1').text().replace(' ',''));
						var curval2=parseInt($('#counter2').text());
						if(curval<=707){
							$('#counter').text(curval+1);
						}
						if(curval1<=12280){
							$('#counter1').text(sdf_FTS((curval1+20),0,' '));
						}
						if(curval2<=245){
							$('#counter2').text(curval2+1);
						}
					}, 2);
					
				}, 500);
			});
	</script>
	<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#menu').slicknav();
		
	});
	</script>
	
	<script type="text/javascript">
    $(document).ready(function(){
       
        var $menu = $("#menuF");
            
        $(window).scroll(function(){
            if ( $(this).scrollTop() > 100 && $menu.hasClass("default") ){
                $menu.fadeOut('fast',function(){
                    $(this).removeClass("default")
                           .addClass("fixed transbg")
                           .fadeIn('fast');
                });
            } else if($(this).scrollTop() <= 100 && $menu.hasClass("fixed")) {
                $menu.fadeOut('fast',function(){
                    $(this).removeClass("fixed transbg")
                           .addClass("default")
                           .fadeIn('fast');
                });
            }
        });
	});
    //jQuery
	</script>
	<script>
		/*menu*/
		function calculateScroll() {
			var contentTop      =   [];
			var contentBottom   =   [];
			var winTop      =   $(window).scrollTop();
			var rangeTop    =   200;
			var rangeBottom =   500;
			$('.navmenu').find('a').each(function(){
				contentTop.push( $( $(this).attr('href') ).offset().top );
				contentBottom.push( $( $(this).attr('href') ).offset().top + $( $(this).attr('href') ).height() );
			})
			$.each( contentTop, function(i){
				if ( winTop > contentTop[i] - rangeTop && winTop < contentBottom[i] - rangeBottom ){
					$('.navmenu li')
					.removeClass('active')
					.eq(i).addClass('active');				
				}
			})
		};
		
		$(document).ready(function(){
			calculateScroll();
			$(window).scroll(function(event) {
				calculateScroll();
			});
			$('.navmenu ul li a').click(function() {  
				$('html, body').animate({scrollTop: $(this.hash).offset().top - 80}, 800);
				return false;
			});
		});		
	</script>	
	<script type="text/javascript" charset="utf-8">

		jQuery(document).ready(function(){
			jQuery(".pretty a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true, social_tools: ''});
			
		});
	</script>
	</body>
	
</html>